name: "my-website"
output_dir: "."
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
    - text: "Data"
      href: data.html
    - text: "Methodology"
      href: methods.html
    - text: "Results"
      href: results.html
